name: Update Postman Collection

on:
  schedule:
    - cron: '0 * * * *'  # Εκτελεί το action κάθε ώρα (μπορείς να το αλλάξεις)

jobs:
  update-collection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Postman Collection
      run: |
        curl -X GET "https://api.postman.com/collections/39579054-83f54cd5-6d8f-4317-87bb-1c7f68ef47d5?access_key=${{ secrets.POSTMAN_API_KEY }}" \
        -H "Accept: application/json" -o postman-collection.json

    - name: Commit and Push changes
      run: |
        # Ρύθμιση του χρήστη και email για το Git
        git config user.name "GitHub Actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Αλλαγή του remote URL ώστε να χρησιμοποιεί το προσωπικό token
        git remote set-url origin https://github.com/Dpapadopoulou96/Postman-Automate-Update-Collection.git
        
        # Προσθήκη των αλλαγών και commit
        git add postman-collection.json
        git commit -m "Update Postman Collection"
        
        # Push στις αλλαγές χρησιμοποιώντας το GH_TOKEN για αυθεντικοποίηση
        git push https://github.com/Dpapadopoulou96/Postman-Automate-Update-Collection.git HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Χρήση του PAT για το git push
